// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © PMoralesDev

//@version=6
indicator("I_MM_00", shorttitle="PMoraleDev_MediasMóviles_SignalAlerts", overlay=true)

// ─────────────────────────────────────────────
// 📌 INPUTS
// ─────────────────────────────────────────────

//🔹 MEDIAS🔹
emaLen = input.int(50,  "Longitud EMA", group = "🔹 MEDIAS")
smaLen = input.int(200, "Longitud SMA", group = "🔹 MEDIAS")

//🔹 TIMEFRAMES🔹 
tEntry = input.timeframe("1",  "Entradas", group="🔹 TIMEFRAMES")
tTrend = input.timeframe("15", "Tendencia", group="🔹 TIMEFRAMES")

//🔹 APPARENCE🔹 
green = input.color(#00ffbb, "Bullish Color", group="Appearance")
red   = input.color(#ff1100, "Bearish Color", group="Appearance")

//🔹 CONSTANTS🔹 
var int trend = 0
var bool alignedBullish = false
var bool alignedBearish = false
var bool position = false


// ─────────────────────────────────────────────
// 📈 CORE
// ─────────────────────────────────────────────
emaEntry = request.security(syminfo.tickerid, tEntry, ta.ema(close, emaLen))
smaEntry = request.security(syminfo.tickerid, tEntry, ta.sma(close, smaLen))
emaTrend = request.security(syminfo.tickerid, tTrend, ta.ema(close, emaLen))
smaTrend = request.security(syminfo.tickerid, tTrend, ta.sma(close, smaLen))

if emaTrend > smaTrend
    trend := 1

if emaTrend < smaTrend
    trend := -1

if trend == 1 and not position
    if ta.crossover(emaEntry, smaEntry)
        label.new(bar_index, high, "Long Entry", style=label.style_label_up, color=color.new(green, 0), textcolor=color.black, size=size.small)
        position := true
        alignedBullish := true
    if ta.crossunder(emaEntry, smaEntry)
        position := false
        alignedBullish := false

if trend == -1 and not position
    if ta.crossunder(emaEntry, smaEntry)
        label.new(bar_index, low, "Short Entry", style=label.style_label_down, color=color.new(red, 0), textcolor=color.black, size=size.small)
        position := true
        alignedBearish := true
    if ta.crossover(emaEntry, smaEntry)
        position := false
        alignedBearish := false

// ─────────────────────────────────────────────
// 🎨 Señales en gráfico
// ─────────────────────────────────────────────

bullEntry = trend == 1 and not position and ta.crossover(emaEntry, smaEntry)
bearEntry = trend == -1 and not position and ta.crossunder(emaEntry, smaEntry)

plotchar(bullEntry ? low : na,, "Bullish Trend", "▲", location.absolute, green, size=size.tiny)
plotchar(bearEntry ? high : na, "Bearish Trend", "▼", location.absolute, red, size=size.tiny)