// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © pmoralesdev

//@version=6
library("mDev-Tools")

//────────────────────────────────────────────//
// 📌 MEDIAS MÓVILES                          //
//────────────────────────────────────────────//

export ema5(src) => ta.ema(src, 5)
export ema10(src) => ta.ema(src, 10)
export ema25(src) => ta.ema(src, 25)
export ema50(src) => ta.ema(src, 50)

export sma20(src) => ta.sma(src,20)
export sma25(src) => ta.sma(src,25)
export sma50(src) => ta.sma(src,50)
export sma100(src) => ta.sma(src,100)
export sma200(src) => ta.sma(src,200)